name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ['1.16', '1.17', '1.18', '1.19']
    name: Build (Go ${{ matrix.go }})
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: go test
      run: go test -v ./...
    - name: go build
      run: go build .
